- name: "Install QEMU"
  hosts: guacamole
  gather_facts: false

  tasks:
    - name: Test connection
      ansible.builtin.ping:

    - name: Install QEMU
      apt:
        name: qemu-guest-agent
        state: latest