- name: "Set ntp for all linux servers"
  hosts: guacamole

  tasks:
    - name: Test connection
      ansible.builtin.ping:

    - name:
      apt:
        name: qemu-guest-agent
        state: latest