- name: Test connectivity to Cisco devices
  hosts: cisco_devices
  gather_facts: no
  tasks:
    - name: Check device hostname to confirm connectivity
      ansible.netcommon.cli_command:
        command: "show version | include uptime"
      register: result
      ignore_errors: yes

    - name: Display hostname result
      debug:
        var: result.stdout
