- name: Create a Proxmox VM
  hosts: proxmox15
  become: yes
  gather_facts: false
  vars:
  proxmox_api_user: 'root'
  proxmox_api_password: 'password'
  proxmox_api_host: proxmox15
  proxmox_api_port: 8006
  proxmox_vm_name: test
  proxmox_vm_node: proxmox15
  proxmox_vm_cores: 2
  proxmox_vm_memory: 2048
  proxmox_vm_disk_size: 20G

- name: Create a Proxmox VM
  proxmox_kvm:
  api_user: proxmox_api_user
  api_password: proxmox_api_password
  api_host: proxmox_api_host
  api_port: proxmox_api_port
  vmid: 777
  node: proxmox_vm_node
  cores: proxmox_vm_cores
  memory: proxmox_vm_memory
  disks:
  - size: proxmox_vm_disk_size
  storage: CephStorage
  state: present