- name: Gather and restart all VMs on a Proxmox node, excluding VMID 800
  hosts: proxmox15
  become: true
  gather_facts: false

  tasks:
    - name: Gather VM IDs using qm list
      shell: "qm list | awk 'NR>1 {print $1}'"
      register: vmid_output

    - name: Filter out VMID 800
      set_fact:
        vmids: "{{ vmid_output.stdout_lines | select('ne', '800') | list }}"