---
- name: Sequentially restart Proxmox servers
  hosts: pvenodes
  become: true
  gather_facts: false
  serial: 1  # Ensures each server is handled one at a time

  vars:
    wait_time: 600  # Time in seconds to wait before starting the check
    check_interval: 30  # Time in seconds between each connectivity check
    max_retries: 20  # Number of retries for checking if the server is up

  tasks:
    - name: Reboot the server
      ansible.builtin.shell: "shutdown -r now"
      async: 1
      poll: 0
      ignore_errors: true

    - name: Wait for server to start rebooting
      pause:
        seconds: "{{ wait_time }}"

    - name: Confirm server is fully functional
      ansible.builtin.ping:
