- name: Gather and restart all VMs on a Proxmox node, excluding VMID 800
  hosts: proxmox15
  become: true
  gather_facts: false

  tasks:
    - name: Gather all VM details
      shell: "pvesh get /cluster/resources --type vm"
      register: vmid_output

    - name: Check if output is valid JSON
      fail:
        msg: "The output from 'pvesh' is not valid JSON: {{ vmid_output.stdout }}"
      when: vmid_output.stdout | length == 0 or (vmid_output.stdout | from_json | type_debug != 'list')

    - name: Extract VM IDs and exclude VMID 800
      set_fact:
        vmids: "{{ vmid_output.stdout | from_json | selectattr('vmid', 'defined') | map(attribute='vmid') | select('ne', 800) | list }}"
